- name: create conf directory
  file:
    path: ~/.config/openstack
    state: directory
    mode: 0755

- name: Create os-client-config file
  template:
    src: cloud.yml.j2
    dest: ~/.config/openstack/clouds.yml
    mode: 0600
    force: yes
    backup: yes

- name: Create env.yml file
  template:
    src: env.yml.j2
    dest: ./env.yml
    mode: 0600
    force: yes
